import JSZip from 'jszip';
import { saveAs } from 'file-saver';

export async function downloadProjectAsZip(
  projectName: string,
  files: { [path: string]: string }
) {
  const zip = new JSZip();

  // Add all files to the zip
  Object.entries(files).forEach(([path, content]) => {
    zip.file(path, content);
  });

  // Add a README if not present
  if (!files['README.md']) {
    zip.file(
      'README.md',
      `# ${projectName}\n\nGenerated by Dev X\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`
    );
  }

  // Generate the zip file
  const blob = await zip.generateAsync({ type: 'blob' });
  
  // Download the zip file
  const fileName = `${projectName.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.zip`;
  saveAs(blob, fileName);
}

export async function downloadSingleFile(fileName: string, content: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  saveAs(blob, fileName);
}
